#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inference-
conda activate LLM
bash inference.sh 'llama-3.2-1b' "-" "None"
bash inference.sh 'llama-3.2-1b' "-" "self"
bash inference.sh 'llama-3.2-1b' "-" "redf"
bash inference.sh 'llama-3.2-1b' "-" "re2df"
bash inference.sh 'llama-3.2-3b' "-" "None"
bash inference.sh 'llama-3.2-3b' "-" "self"
bash inference.sh 'llama-3.2-3b' "-" "redf"
bash inference.sh 'llama-3.2-3b' "-" "re2df"