#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inference-
conda activate LLM-2
bash inference.sh 'llama-3.1-8b' "-" "None"
bash inference.sh 'llama-3.1-8b' "-" "self"
bash inference.sh 'llama-3.1-8b' "-" "redf"
bash inference.sh 'llama-3.1-8b' "-" "are2df"
bash inference.sh 'llama-3.1-70b' "-" "None"
bash inference.sh 'llama-3.1-70b' "-" "self"
bash inference.sh 'llama-3.1-70b' "-" "redf"
bash inference.sh 'llama-3.1-70b' "-" "are2df"