python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/LogP+"     --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/LogP-"     --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/TPSA+"     --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/TPSA-"     --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/HBD+"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/HBD-"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/HBA+"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/HBA-"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/QED+"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/single/QED-"      --refine $2 --refine_steps 3 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+TPSA+" --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+TPSA-" --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-TPSA+" --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-TPSA-" --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+HBD+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+HBD-"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-HBD+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-HBD-"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+HBA+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+HBA-"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-HBA+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-HBA-"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+QED+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP+QED-"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-QED+"  --refine $2 --refine_steps 4 --hit_thres $3
python inference.py --llm_model_name $1 --data "MGen/MModify/ZINC500/multi/LogP-QED-"  --refine $2 --refine_steps 4 --hit_thres $3