#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inference-
conda activate LLM
bash inference.sh 'llama-3.1-8b'  "-" "None"
bash inference.sh 'llama-3.1-8b'  "-" "self"
bash inference.sh 'llama-3.1-8b'  "-" "retrieve"
bash inference.sh 'llama-3.1-8b'  "-" "molt-retrieve"
bash inference.sh 'llama-3.1-70b' "-" "None"
bash inference.sh 'llama-3.1-70b' "-" "self"
bash inference.sh 'llama-3.1-70b' "-" "retrieve"
bash inference.sh 'llama-3.1-70b' "-" "molt-retrieve"