#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@qa-a40-005
#$ -l gpu=2
#$ -N inference+
conda activate LLM
bash inference.sh 'qwen2.5-3b' "+" "None"
bash inference.sh 'qwen2.5-3b' "+" "self"
bash inference.sh 'qwen2.5-3b' "+" "redf"
bash inference.sh 'qwen2.5-3b' "+" "re2df"
bash inference.sh 'qwen2.5-7b' "+" "None"
bash inference.sh 'qwen2.5-7b' "+" "self"
bash inference.sh 'qwen2.5-7b' "+" "redf"
bash inference.sh 'qwen2.5-7b' "+" "re2df"