#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=1
#$ -N inference-
conda activate LLM
bash inference.sh 'qwen2.5-7b'  "-" "None"
bash inference.sh 'qwen2.5-7b'  "-" "self"
bash inference.sh 'qwen2.5-7b'  "-" "retrieve"
bash inference.sh 'qwen2.5-7b'  "-" "molt-retrieve"
bash inference.sh 'qwen2.5-14b' "-" "None"
bash inference.sh 'qwen2.5-14b' "-" "self"
bash inference.sh 'qwen2.5-14b' "-" "retrieve"
bash inference.sh 'qwen2.5-14b' "-" "molt-retrieve"